name: "[CD] Continuous Delivery"

# Sempre que tiver um commit ou um PR for aberto
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize]
on:
  pull_request:
    types: [opened, synchronize]
env:
  VERCEL_ORG_ID: PwISSZXZyyiHyJaZ2dG0c18B
  VERCEL_PROJECT_ID: prj_UXzCt16RyNuzHRSGZdt19PG4MCXh

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## =================
      - name: "Debug"
        run: |
          ls -la
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Lint"
        run: "npx vercel --prod --token=tEmViSBOak4USZgVGNHK2CTl"
